import type { Drop } from './types';

// Small, focused reps that isolate one piece of a larger pattern before composition.
export const CHUNK_DRILLS = [
  {id:'binary-midpoint',track:'Binary Search',concept:'Midpoint calculation',chunk:'CHUNK 1 · SETUP',level:2,color:'cyan',label:'BISECT',seconds:20,xp:120,task:'safe midpoint',description:'Return the midpoint index between inclusive bounds left and right.',input:'left = 3, right = 10',output:'6',signature:'left, right',hint:'Use integer floor division.',insight:'the midpoint splits the remaining search interval',answer:'(left + right) // 2',tests:[{args:[3,10],expected:6,label:'3, 10'},{args:[0,1],expected:0,label:'0, 1'},{args:[8,8],expected:8,label:'8, 8'}]},
  {id:'first-true',track:'Binary Search',concept:'First-true boundary',chunk:'CHUNK 2 · UPDATE',level:3,mode:'code',color:'violet',label:'BOUND',seconds:65,xp:240,task:'first true index',description:'The list changes from False to True once. Return the first True index, or len(flags).',input:'flags = [False, False, True, True]',output:'2',signature:'flags',hint:'Keep a half-open [left, right) search interval.',insight:'boundary search finds where a monotonic predicate flips',tests:[{args:[[false,false,true,true]],expected:2,label:'flip at 2'},{args:[[true,true]],expected:0,label:'all true'},{args:[[false,false]],expected:2,label:'no true'}]},
  {id:'window-count',track:'Sliding Window',concept:'Window boundaries',chunk:'CHUNK 1 · SHAPE',level:2,color:'lime',label:'WINDOW',seconds:20,xp:120,task:'number of k-wide windows',description:'Return how many consecutive windows of width k fit in nums.',input:'nums = [1,2,3,4,5], k = 3',output:'3',signature:'nums, k',hint:'Count the valid starting indices.',insight:'a width-k window has n−k+1 possible starts',answer:'max(0, len(nums) - k + 1)',tests:[{args:[[1,2,3,4,5],3],expected:3,label:'five values, k=3'},{args:[[1,2],2],expected:1,label:'exact fit'},{args:[[1],2],expected:0,label:'too short'}]},
  {id:'initial-window',track:'Sliding Window',concept:'Initial window state',chunk:'CHUNK 2 · INITIALIZE',level:2,color:'orange',label:'WINDOW',seconds:22,xp:130,task:'first window sum',description:'Return the sum of the first k values.',input:'nums = [2,1,5,1], k = 3',output:'8',signature:'nums, k',hint:'Slice exactly the first k items.',insight:'rolling windows begin with one explicitly computed state',answer:'sum(nums[:k])',tests:[{args:[[2,1,5,1],3],expected:8,label:'first three'},{args:[[4,5],1],expected:4,label:'k=1'},{args:[[],0],expected:0,label:'empty window'}]},
  {id:'prefix-subtract',track:'Prefix Sums',concept:'Range subtraction',chunk:'CHUNK 2 · QUERY',level:2,color:'pink',label:'PREFIX',seconds:24,xp:140,task:'one range total',description:'prefix[i] stores the sum before index i. Return the inclusive [left, right] total.',input:'prefix = [0,2,6,7,14], left = 1, right = 3',output:'12',signature:'prefix, left, right',hint:'Subtract the prefix before left from the prefix after right.',insight:'two cumulative totals isolate any contiguous range',answer:'prefix[right + 1] - prefix[left]',tests:[{args:[[0,2,6,7,14],1,3],expected:12,label:'middle range'},{args:[[0,5],0,0],expected:5,label:'one item'},{args:[[0,1,3,6],0,2],expected:6,label:'whole range'}]},
  {id:'prefix-seed',track:'Prefix Sums',concept:'Zero-seeded prefix array',chunk:'CHUNK 1 · BUILD',level:2,color:'cyan',label:'PREFIX',seconds:30,xp:150,task:'prefix array with zero seed',description:'Return cumulative sums with an initial zero before any values are consumed.',input:'nums = [2,4,1]',output:'[0,2,6,7]',signature:'nums',hint:'Prepend zero to running totals.',insight:'the zero seed removes special cases at the left boundary',answer:'[0] + list(__import__("itertools").accumulate(nums))',tests:[{args:[[2,4,1]],expected:[0,2,6,7],label:'three values'},{args:[[]],expected:[0],label:'empty'},{args:[[-2,3]],expected:[0,-2,1],label:'mixed signs'}]},
  {id:'dp-choice',track:'Dynamic Programming',concept:'Take-or-skip transition',chunk:'CHUNK 1 · TRANSITION',level:2,color:'orange',label:'DP',seconds:22,xp:140,task:'best local choice',description:'Return the better value between skipping and taking the current option.',input:'skip = 8, take = 11',output:'11',signature:'skip, take',hint:'A DP transition often chooses the best predecessor.',insight:'complex recurrences are built from small explicit choices',answer:'max(skip, take)',tests:[{args:[8,11],expected:11,label:'take wins'},{args:[10,3],expected:10,label:'skip wins'},{args:[-2,-5],expected:-2,label:'negative values'}]},
  {id:'fibonacci-state',track:'Dynamic Programming',concept:'Rolling previous states',chunk:'CHUNK 2 · MEMORY',level:3,mode:'code',color:'lime',label:'DP',seconds:60,xp:230,task:'nth Fibonacci value',description:'Return F(n), where F(0)=0 and F(1)=1, using rolling state.',input:'n = 7',output:'13',signature:'n',hint:'Update the previous two values together.',insight:'many one-dimensional DPs only need their last two states',tests:[{args:[7],expected:13,label:'n=7'},{args:[0],expected:0,label:'base zero'},{args:[1],expected:1,label:'base one'}]},
  {id:'grid-neighbors',track:'Graphs & Grids',concept:'Implicit grid edges',chunk:'CHUNK 1 · NEIGHBORS',level:3,mode:'code',color:'cyan',label:'GRID',seconds:70,xp:250,task:'valid grid neighbors',description:'Return sorted four-directional neighbors inside a rows × cols grid.',input:'row = 1, col = 1, rows = 3, cols = 3',output:'[[0,1],[1,0],[1,2],[2,1]]',signature:'row, col, rows, cols',hint:'Try four fixed direction offsets and keep in-bounds cells.',insight:'grid graphs generate edges from coordinates on demand',tests:[{args:[1,1,3,3],expected:[[0,1],[1,0],[1,2],[2,1]],label:'center'},{args:[0,0,2,2],expected:[[0,1],[1,0]],label:'corner'},{args:[0,0,1,1],expected:[],label:'one cell'}]},
  {id:'build-adjacency',track:'Graphs & Grids',concept:'Adjacency-list construction',chunk:'CHUNK 2 · REPRESENT',level:3,mode:'code',color:'violet',label:'GRAPH',seconds:75,xp:270,task:'undirected adjacency lists',description:'Build sorted neighbor lists for nodes 0 through n−1 from undirected edges.',input:'n = 4, edges = [[0,1],[0,2],[2,3]]',output:'[[1,2],[0],[0,3],[2]]',signature:'n, edges',hint:'Every undirected edge is stored in both directions.',insight:'an adjacency list makes each node’s outgoing work explicit',tests:[{args:[4,[[0,1],[0,2],[2,3]]],expected:[[1,2],[0],[0,3],[2]],label:'four nodes'},{args:[3,[]],expected:[[],[],[]],label:'isolated'},{args:[2,[[0,1]]],expected:[[1],[0]],label:'one edge'}]},
  {id:'interval-overlap',track:'Intervals & Greedy',concept:'Overlap predicate',chunk:'CHUNK 1 · COMPARE',level:2,color:'pink',label:'RANGE',seconds:24,xp:140,task:'overlap check',description:'Return whether two inclusive [start, end] ranges overlap.',input:'a = [1,4], b = [3,7]',output:'True',signature:'a, b',hint:'They overlap unless one finishes before the other starts.',insight:'one predicate powers interval merging and scheduling',answer:'a[0] <= b[1] and b[0] <= a[1]',tests:[{args:[[1,4],[3,7]],expected:true,label:'overlap'},{args:[[1,2],[3,4]],expected:false,label:'separate'},{args:[[1,3],[3,5]],expected:true,label:'touching'}]},
  {id:'sort-intervals',track:'Intervals & Greedy',concept:'Sort by start boundary',chunk:'CHUNK 2 · ORDER',level:2,color:'orange',label:'RANGE',seconds:25,xp:145,task:'ranges ordered by start',description:'Return intervals ordered by starting value.',input:'ranges = [[8,10],[1,3],[4,6]]',output:'[[1,3],[4,6],[8,10]]',signature:'ranges',hint:'Use sorted with a key selecting index 0.',insight:'ordering turns global interval relationships into local ones',answer:'sorted(ranges, key=lambda interval: interval[0])',tests:[{args:[[[8,10],[1,3],[4,6]]],expected:[[1,3],[4,6],[8,10]],label:'shuffled'},{args:[[]],expected:[],label:'empty'},{args:[[[2,5]]],expected:[[2,5]],label:'one range'}]},
  {id:'k-smallest',track:'Heaps',concept:'Top-k selection API',chunk:'CHUNK 1 · SELECT',level:3,color:'lime',label:'HEAP',seconds:30,xp:160,task:'k smallest values',description:'Return the k smallest values in ascending order.',input:'nums = [7,2,5,1,9], k = 3',output:'[1,2,5]',signature:'nums, k',hint:'heapq provides nsmallest for bounded selection.',insight:'heap selection avoids fully sorting large inputs',answer:'__import__("heapq").nsmallest(k, nums)',tests:[{args:[[7,2,5,1,9],3],expected:[1,2,5],label:'k=3'},{args:[[4,4,2],2],expected:[2,4],label:'duplicates'},{args:[[1],1],expected:[1],label:'one value'}]},
  {id:'heap-order',track:'Heaps',concept:'Push/pop heap invariant',chunk:'CHUNK 2 · OPERATE',level:3,mode:'code',color:'cyan',label:'HEAP',seconds:70,xp:260,task:'heap removal order',description:'Push every number into a min-heap, then return values in pop order.',input:'nums = [5,1,4,2]',output:'[1,2,4,5]',signature:'nums',hint:'Use heapq.heappush followed by repeated heappop.',insight:'the smallest value remains at the root after every operation',tests:[{args:[[5,1,4,2]],expected:[1,2,4,5],label:'four values'},{args:[[]],expected:[],label:'empty'},{args:[[3,3,1]],expected:[1,3,3],label:'duplicates'}]},
  {id:'binary-strings',track:'Backtracking',concept:'Binary decision tree',chunk:'CHUNK 1 · BRANCH',level:3,mode:'code',color:'violet',label:'SEARCH',seconds:85,xp:290,task:'all binary strings',description:'Return every length-n binary string in 0-before-1 depth-first order.',input:'n = 2',output:'["00","01","10","11"]',signature:'n',hint:'At each depth, choose 0, recurse, then choose 1.',insight:'backtracking enumerates leaves of an explicit choice tree',tests:[{args:[2],expected:['00','01','10','11'],label:'n=2'},{args:[1],expected:['0','1'],label:'n=1'},{args:[0],expected:[''],label:'n=0'}]},
  {id:'is-leaf',track:'Trees',concept:'Tree base cases',chunk:'CHUNK 1 · BASE CASE',level:3,color:'pink',label:'TREE',seconds:25,xp:145,task:'leaf node check',description:'Trees use [value, left, right]. Return whether tree is a non-empty leaf.',input:'tree = [7,None,None]',output:'True',signature:'tree',hint:'A leaf exists and has no left or right child.',insight:'clear base cases keep recursive tree code small',answer:'tree is not None and tree[1] is None and tree[2] is None',tests:[{args:[[7,null,null]],expected:true,label:'leaf'},{args:[[7,[2,null,null],null]],expected:false,label:'has child'},{args:[null],expected:false,label:'empty'}]},
] satisfies Drop[];
