import type { Drop } from './types';

// Original drills built around common programming patterns. Problem wording is intentionally
// compact so each round begins with retrieval rather than a long reading phase.
export const CURRICULUM = [
  {
    id: 'largest', track: 'Python Foundations', concept: 'Built-ins · max', level: 1,
    color: 'orange', label: 'MAX', seconds: 18, xp: 80, task: 'largest number',
    description: 'Return the highest value in the list.', input: 'nums = [4, 9, 2, 7]', output: '9',
    signature: 'nums', hint: 'Python has a built-in opposite of min.', insight: 'max scans the values once · O(n)', answer: 'max(nums)',
    tests: [{ args: [[4,9,2,7]], expected: 9, label: '[4, 9, 2, 7]' }, { args: [[-8,-2,-5]], expected: -2, label: '[-8, -2, -5]' }, { args: [[6]], expected: 6, label: '[6]' }],
  },
  {
    id: 'total', track: 'Python Foundations', concept: 'Built-ins · sum', level: 1,
    color: 'cyan', label: 'SUM', seconds: 18, xp: 80, task: 'total of all numbers',
    description: 'Add every value and return the total.', input: 'nums = [4, 2, 7]', output: '13',
    signature: 'nums', hint: 'Use the built-in made for totals.', insight: 'sum is clearer than a manual accumulator', answer: 'sum(nums)',
    tests: [{ args: [[4,2,7]], expected: 13, label: '[4, 2, 7]' }, { args: [[]], expected: 0, label: '[]' }, { args: [[-2,5,-1]], expected: 2, label: '[-2, 5, -1]' }],
  },
  {
    id: 'last-item', track: 'Python Foundations', concept: 'Negative indexing', level: 1,
    color: 'violet', label: 'INDEX', seconds: 16, xp: 80, task: 'last item',
    description: 'Return the final item without calculating the list length.', input: 'items = ["a", "b", "c"]', output: '"c"',
    signature: 'items', hint: 'Python indices can count backward from zero.', insight: 'index -1 always addresses the final item', answer: 'items[-1]',
    tests: [{ args: [['a','b','c']], expected: 'c', label: '["a", "b", "c"]' }, { args: [[9]], expected: 9, label: '[9]' }, { args: [[true,false]], expected: false, label: '[True, False]' }],
  },
  {
    id: 'squares', track: 'Python Foundations', concept: 'List comprehensions', level: 1,
    color: 'pink', label: 'MAP', seconds: 23, xp: 100, task: 'square every number',
    description: 'Return a new list containing each number multiplied by itself.', input: 'nums = [1, 3, 4]', output: '[1, 9, 16]',
    signature: 'nums', hint: 'Build a list with [expression for item in items].', insight: 'comprehensions express map operations compactly', answer: '[n * n for n in nums]',
    tests: [{ args: [[1,3,4]], expected: [1,9,16], label: '[1, 3, 4]' }, { args: [[-2,0,5]], expected: [4,0,25], label: '[-2, 0, 5]' }, { args: [[]], expected: [], label: '[]' }],
  },
  {
    id: 'positives', track: 'Python Foundations', concept: 'Filtering comprehensions', level: 1,
    color: 'lime', label: 'FILTER', seconds: 23, xp: 100, task: 'positive numbers',
    description: 'Keep values greater than zero, preserving their order.', input: 'nums = [-2, 0, 4, -1, 7]', output: '[4, 7]',
    signature: 'nums', hint: 'Add an if condition to a list comprehension.', insight: 'the trailing if filters before values enter the list', answer: '[n for n in nums if n > 0]',
    tests: [{ args: [[-2,0,4,-1,7]], expected: [4,7], label: '[-2, 0, 4, -1, 7]' }, { args: [[1,2]], expected: [1,2], label: '[1, 2]' }, { args: [[-3,0]], expected: [], label: '[-3, 0]' }],
  },
  {
    id: 'all-positive', track: 'Python Foundations', concept: 'Predicates · all', level: 1,
    color: 'cyan', label: 'ALL', seconds: 22, xp: 100, task: 'all values positive',
    description: 'Return True only when every number is greater than zero.', input: 'nums = [3, 1, 8]', output: 'True',
    signature: 'nums', hint: 'Combine all with a generator expression.', insight: 'all short-circuits at the first False value', answer: 'all(n > 0 for n in nums)',
    tests: [{ args: [[3,1,8]], expected: true, label: '[3, 1, 8]' }, { args: [[2,0,4]], expected: false, label: '[2, 0, 4]' }, { args: [[]], expected: true, label: '[]' }],
  },
  {
    id: 'vowel-count', track: 'Python Foundations', concept: 'Membership + generators', level: 1,
    color: 'orange', label: 'COUNT', seconds: 24, xp: 110, task: 'number of vowels',
    description: 'Count vowels in the text, ignoring letter case.', input: 'text = "Leetris"', output: '3',
    signature: 'text', hint: 'Lower each character and test membership in "aeiou".', insight: 'membership tests compose naturally with sum', answer: 'sum(char.lower() in "aeiou" for char in text)',
    tests: [{ args: ['Leetris'], expected: 3, label: '"Leetris"' }, { args: ['RHYTHM'], expected: 0, label: '"RHYTHM"' }, { args: ['AEIOU'], expected: 5, label: '"AEIOU"' }],
  },
  {
    id: 'pair-up', track: 'Python Foundations', concept: 'Iteration · zip', level: 1,
    color: 'violet', label: 'ZIP', seconds: 22, xp: 110, task: 'paired lists',
    description: 'Pair items at matching positions and return them as two-item lists.', input: 'a = [1, 2], b = ["x", "y"]', output: '[[1, "x"], [2, "y"]]',
    signature: 'a, b', hint: 'zip joins parallel iterables; convert each pair to a list.', insight: 'zip stops at the shorter iterable', answer: '[list(pair) for pair in zip(a, b)]',
    tests: [{ args: [[1,2],['x','y']], expected: [[1,'x'],[2,'y']], label: '[1, 2], ["x", "y"]' }, { args: [[],[]], expected: [], label: '[], []' }, { args: [[1,2,3],['a']], expected: [[1,'a']], label: '[1, 2, 3], ["a"]' }],
  },
  {
    id: 'two-sum', track: 'Hash Maps', concept: 'Complement lookup', level: 2, mode: 'code',
    color: 'lime', label: 'HASH', seconds: 70, xp: 240, task: 'indices of a target pair',
    description: 'Return two indices whose values add to target. Exactly one pair exists.', input: 'nums = [2, 7, 11, 15], target = 9', output: '[0, 1]',
    signature: 'nums, target', hint: 'Store each value’s index while looking for its complement.', insight: 'a hash map turns repeated search into O(n)',
    tests: [{ args: [[2,7,11,15],9], expected: [0,1], label: '[2, 7, 11, 15], 9' }, { args: [[3,2,4],6], expected: [1,2], label: '[3, 2, 4], 6' }, { args: [[3,3],6], expected: [0,1], label: '[3, 3], 6' }],
  },
  {
    id: 'anagram', track: 'Hash Maps', concept: 'Frequency counting', level: 2,
    color: 'cyan', label: 'FREQ', seconds: 30, xp: 150, task: 'anagram check',
    description: 'Return True when both strings contain identical character counts.', input: 'a = "listen", b = "silent"', output: 'True',
    signature: 'a, b', hint: 'Sorted characters can act as a canonical form.', insight: 'canonical forms make equality easy to test', answer: 'sorted(a) == sorted(b)',
    tests: [{ args: ['listen','silent'], expected: true, label: '"listen", "silent"' }, { args: ['rat','car'], expected: false, label: '"rat", "car"' }, { args: ['',''], expected: true, label: '"", ""' }],
  },
  {
    id: 'first-unique', track: 'Hash Maps', concept: 'Count then scan', level: 2, mode: 'code',
    color: 'pink', label: 'FREQ', seconds: 60, xp: 220, task: 'first unique character',
    description: 'Return the index of the first character appearing once, or -1.', input: 'text = "loveleetcode"', output: '2',
    signature: 'text', hint: 'Count once, then scan left-to-right.', insight: 'separate counting from ordering concerns · O(n)',
    tests: [{ args: ['loveleetcode'], expected: 2, label: '"loveleetcode"' }, { args: ['aabb'], expected: -1, label: '"aabb"' }, { args: ['z'], expected: 0, label: '"z"' }],
  },
  {
    id: 'majority', track: 'Hash Maps', concept: 'Frequency dominance', level: 2,
    color: 'orange', label: 'MODE', seconds: 28, xp: 150, task: 'majority value',
    description: 'Return the value occurring more than half the time.', input: 'nums = [2, 2, 1, 2]', output: '2',
    signature: 'nums', hint: 'The most frequent value is the mode.', insight: 'max can select a key using a custom key function', answer: 'max(set(nums), key=nums.count)',
    tests: [{ args: [[2,2,1,2]], expected: 2, label: '[2, 2, 1, 2]' }, { args: [[3,3,4,2,3,3,3]], expected: 3, label: '[3, 3, 4, 2, 3, 3, 3]' }, { args: [[1]], expected: 1, label: '[1]' }],
  },
  {
    id: 'valid-palindrome', track: 'Two Pointers', concept: 'Converging pointers', level: 3, mode: 'code',
    color: 'violet', label: '2 PTR', seconds: 75, xp: 260, task: 'clean palindrome check',
    description: 'Ignore punctuation and case; return whether the text reads the same backward.', input: 'text = "A man, a plan, a canal: Panama"', output: 'True',
    signature: 'text', hint: 'Move left and right inward, skipping non-alphanumeric characters.', insight: 'two pointers avoid allocating a reversed copy',
    tests: [{ args: ['A man, a plan, a canal: Panama'], expected: true, label: 'Panama phrase' }, { args: ['race a car'], expected: false, label: '"race a car"' }, { args: [' '], expected: true, label: '" "' }],
  },
  {
    id: 'sorted-pair', track: 'Two Pointers', concept: 'Directional elimination', level: 3, mode: 'code',
    color: 'cyan', label: '2 PTR', seconds: 70, xp: 260, task: 'pair in a sorted list',
    description: 'Return zero-based indices of two values adding to target.', input: 'nums = [2, 3, 4, 8], target = 6', output: '[0, 2]',
    signature: 'nums, target', hint: 'Start at both ends; move the side that cannot work.', insight: 'sorted order lets each comparison eliminate a region',
    tests: [{ args: [[2,3,4,8],6], expected: [0,2], label: '[2, 3, 4, 8], 6' }, { args: [[-3,1,5,9],6], expected: [0,3], label: '[-3, 1, 5, 9], 6' }, { args: [[1,2],3], expected: [0,1], label: '[1, 2], 3' }],
  },
  {
    id: 'sorted-squares', track: 'Two Pointers', concept: 'Merge from extremes', level: 3, mode: 'code',
    color: 'lime', label: '2 PTR', seconds: 80, xp: 280, task: 'sorted squares',
    description: 'Square a sorted list and return the squares in sorted order.', input: 'nums = [-4, -1, 0, 3, 10]', output: '[0, 1, 9, 16, 100]',
    signature: 'nums', hint: 'The largest square must come from one of the two ends.', insight: 'fill the result backward using two pointers · O(n)',
    tests: [{ args: [[-4,-1,0,3,10]], expected: [0,1,9,16,100], label: '[-4, -1, 0, 3, 10]' }, { args: [[-3,-2]], expected: [4,9], label: '[-3, -2]' }, { args: [[]], expected: [], label: '[]' }],
  },
  {
    id: 'max-water', track: 'Two Pointers', concept: 'Greedy pointer movement', level: 3, mode: 'code',
    color: 'orange', label: '2 PTR', seconds: 90, xp: 320, task: 'largest water container',
    description: 'Choose two heights maximizing width × the shorter height.', input: 'heights = [1, 8, 6, 2, 5, 4, 8, 3, 7]', output: '49',
    signature: 'heights', hint: 'Moving the taller wall cannot improve the current bottleneck.', insight: 'move only the shorter wall · O(n)',
    tests: [{ args: [[1,8,6,2,5,4,8,3,7]], expected: 49, label: 'classic sample' }, { args: [[1,1]], expected: 1, label: '[1, 1]' }, { args: [[1,2,1]], expected: 2, label: '[1, 2, 1]' }],
  },
  {
    id: 'valid-brackets', track: 'Stacks', concept: 'Matching stack', level: 3, mode: 'code',
    color: 'pink', label: 'STACK', seconds: 65, xp: 250, task: 'balanced brackets',
    description: 'Return True when every bracket closes in the correct order.', input: 'text = "{[()]}"', output: 'True',
    signature: 'text', hint: 'Push openers; each closer must match the latest opener.', insight: 'a stack remembers the most recent unfinished pair',
    tests: [{ args: ['{[()]}'], expected: true, label: '"{[()]}"' }, { args: ['([)]'], expected: false, label: '"([)]"' }, { args: [''], expected: true, label: '""' }],
  },
  {
    id: 'adjacent-dupes', track: 'Stacks', concept: 'Cancellation stack', level: 3, mode: 'code',
    color: 'violet', label: 'STACK', seconds: 65, xp: 250, task: 'remove adjacent pairs',
    description: 'Repeatedly remove equal neighboring characters and return what remains.', input: 'text = "abbaca"', output: '"ca"',
    signature: 'text', hint: 'The stack top is the only character that can cancel the next one.', insight: 'local cancellations become a single linear scan',
    tests: [{ args: ['abbaca'], expected: 'ca', label: '"abbaca"' }, { args: ['azxxzy'], expected: 'ay', label: '"azxxzy"' }, { args: ['aa'], expected: '', label: '"aa"' }],
  },
  {
    id: 'daily-warmer', track: 'Stacks', concept: 'Monotonic stack', level: 4, mode: 'code',
    color: 'orange', label: 'MONO', seconds: 110, xp: 360, task: 'days until warmer',
    description: 'For each temperature, return how many days until a warmer one, or 0.', input: 'temps = [73, 74, 75, 71, 69, 72, 76, 73]', output: '[1, 1, 4, 2, 1, 1, 0, 0]',
    signature: 'temps', hint: 'Keep indices whose warmer day has not been found.', insight: 'each index enters and leaves the stack once · O(n)',
    tests: [{ args: [[73,74,75,71,69,72,76,73]], expected: [1,1,4,2,1,1,0,0], label: 'eight days' }, { args: [[30,40,50,60]], expected: [1,1,1,0], label: 'rising' }, { args: [[30,20,10]], expected: [0,0,0], label: 'falling' }],
  },
  {
    id: 'binary-search', track: 'Binary Search', concept: 'Halving search space', level: 3, mode: 'code',
    color: 'cyan', label: 'BISECT', seconds: 70, xp: 270, task: 'target index',
    description: 'Find target in a sorted list, returning its index or -1.', input: 'nums = [-1, 0, 3, 5, 9, 12], target = 9', output: '4',
    signature: 'nums, target', hint: 'Compare the middle value and discard half.', insight: 'binary search reduces n items to log₂(n) checks',
    tests: [{ args: [[-1,0,3,5,9,12],9], expected: 4, label: 'target present' }, { args: [[-1,0,3,5,9,12],2], expected: -1, label: 'target absent' }, { args: [[5],5], expected: 0, label: 'one item' }],
  },
  {
    id: 'lower-bound', track: 'Binary Search', concept: 'Boundary search', level: 4, mode: 'code',
    color: 'lime', label: 'BOUND', seconds: 85, xp: 310, task: 'insertion position',
    description: 'Return the first index where target could be inserted without breaking sort order.', input: 'nums = [1, 3, 5, 6], target = 2', output: '1',
    signature: 'nums, target', hint: 'Search for the first value greater than or equal to target.', insight: 'binary search can locate boundaries, not only exact values',
    tests: [{ args: [[1,3,5,6],2], expected: 1, label: '[1, 3, 5, 6], 2' }, { args: [[1,3,5,6],7], expected: 4, label: 'after end' }, { args: [[1,3,5,6],0], expected: 0, label: 'before start' }],
  },
  {
    id: 'window-sum', track: 'Sliding Window', concept: 'Fixed-size window', level: 3, mode: 'code',
    color: 'violet', label: 'WINDOW', seconds: 75, xp: 280, task: 'largest k-length sum',
    description: 'Return the greatest sum among all consecutive groups of k values.', input: 'nums = [2, 1, 5, 1, 3, 2], k = 3', output: '9',
    signature: 'nums, k', hint: 'Subtract the outgoing value when adding the incoming one.', insight: 'reuse the previous window instead of summing again · O(n)',
    tests: [{ args: [[2,1,5,1,3,2],3], expected: 9, label: 'six values, k=3' }, { args: [[2,3,4,1,5],2], expected: 7, label: 'five values, k=2' }, { args: [[-4,-2,-7],2], expected: -6, label: 'negative values' }],
  },
  {
    id: 'longest-unique', track: 'Sliding Window', concept: 'Variable-size window', level: 4, mode: 'code',
    color: 'pink', label: 'WINDOW', seconds: 100, xp: 350, task: 'longest unique substring',
    description: 'Return the longest substring length containing no repeated character.', input: 'text = "abcabcbb"', output: '3',
    signature: 'text', hint: 'Move the left edge past the previous copy of a repeated character.', insight: 'the window maintains exactly the valid region · O(n)',
    tests: [{ args: ['abcabcbb'], expected: 3, label: '"abcabcbb"' }, { args: ['bbbbb'], expected: 1, label: '"bbbbb"' }, { args: ['pwwkew'], expected: 3, label: '"pwwkew"' }],
  },
  {
    id: 'prefix-range', track: 'Prefix Sums', concept: 'Precomputed cumulative totals', level: 3, mode: 'code',
    color: 'orange', label: 'PREFIX', seconds: 85, xp: 300, task: 'many range sums',
    description: 'Return the inclusive sum for every [left, right] query.', input: 'nums = [2, 4, 1, 7], queries = [[0, 1], [1, 3]]', output: '[6, 12]',
    signature: 'nums, queries', hint: 'Build totals where prefix[i] stores everything before i.', insight: 'one O(n) setup makes every query O(1)',
    tests: [{ args: [[2,4,1,7],[[0,1],[1,3]]], expected: [6,12], label: 'two ranges' }, { args: [[5],[[0,0]]], expected: [5], label: 'one value' }, { args: [[1,2,3],[[0,2],[1,1]]], expected: [6,2], label: 'whole and middle' }],
  },
  {
    id: 'climb-stairs', track: 'Dynamic Programming', concept: 'One-dimensional recurrence', level: 4, mode: 'code',
    color: 'lime', label: 'DP', seconds: 80, xp: 320, task: 'ways to climb',
    description: 'Count ways to reach step n using jumps of one or two steps.', input: 'n = 5', output: '8',
    signature: 'n', hint: 'Ways(n) = Ways(n−1) + Ways(n−2).', insight: 'keep only the two previous states · O(1) space',
    tests: [{ args: [5], expected: 8, label: 'n = 5' }, { args: [2], expected: 2, label: 'n = 2' }, { args: [1], expected: 1, label: 'n = 1' }],
  },
  {
    id: 'house-robber', track: 'Dynamic Programming', concept: 'Take-or-skip recurrence', level: 4, mode: 'code',
    color: 'violet', label: 'DP', seconds: 100, xp: 360, task: 'maximum non-adjacent sum',
    description: 'Choose values with no adjacent selections and maximize their total.', input: 'nums = [2, 7, 9, 3, 1]', output: '12',
    signature: 'nums', hint: 'At each value, compare skipping it with taking it plus the result two steps back.', insight: 'each decision collapses to two prior optimal states',
    tests: [{ args: [[2,7,9,3,1]], expected: 12, label: '[2, 7, 9, 3, 1]' }, { args: [[1,2,3,1]], expected: 4, label: '[1, 2, 3, 1]' }, { args: [[]], expected: 0, label: '[]' }],
  },
  {
    id: 'coin-change', track: 'Dynamic Programming', concept: 'Unbounded choices', level: 5, mode: 'code',
    color: 'cyan', label: 'DP', seconds: 130, xp: 430, task: 'fewest coins',
    description: 'Return the fewest coins totaling amount, or -1 when impossible.', input: 'coins = [1, 2, 5], amount = 11', output: '3',
    signature: 'coins, amount', hint: 'Build the best answer for every smaller amount first.', insight: 'bottom-up DP reuses solved sub-amounts',
    tests: [{ args: [[1,2,5],11], expected: 3, label: '[1, 2, 5], 11' }, { args: [[2],3], expected: -1, label: '[2], 3' }, { args: [[1],0], expected: 0, label: '[1], 0' }],
  },
  {
    id: 'word-break', track: 'Dynamic Programming', concept: 'Prefix decomposition', level: 5, mode: 'code',
    color: 'pink', label: 'DP', seconds: 140, xp: 450, task: 'segmentable sentence',
    description: 'Return whether text can be split entirely into dictionary words.', input: 'text = "leetcode", words = ["leet", "code"]', output: 'True',
    signature: 'text, words', hint: 'Let dp[i] mean the prefix ending at i can be segmented.', insight: 'valid prefixes become stepping stones for longer ones',
    tests: [{ args: ['leetcode',['leet','code']], expected: true, label: '"leetcode"' }, { args: ['applepenapple',['apple','pen']], expected: true, label: 'reused word' }, { args: ['catsandog',['cats','dog','sand','and','cat']], expected: false, label: 'impossible suffix' }],
  },
  {
    id: 'islands', track: 'Graphs & Grids', concept: 'Flood fill', level: 5, mode: 'code',
    color: 'orange', label: 'DFS', seconds: 150, xp: 480, task: 'number of islands',
    description: 'Count connected groups of 1s joined vertically or horizontally.', input: 'grid = [[1,1,0],[0,1,0],[1,0,1]]', output: '3',
    signature: 'grid', hint: 'When land is found, explore and mark its entire connected region.', insight: 'each cell is visited at most once · O(rows × cols)',
    tests: [{ args: [[[1,1,0],[0,1,0],[1,0,1]]], expected: 3, label: 'three regions' }, { args: [[[1,1],[1,1]]], expected: 1, label: 'one region' }, { args: [[[0,0],[0,0]]], expected: 0, label: 'water only' }],
  },
  {
    id: 'components', track: 'Graphs & Grids', concept: 'Graph traversal', level: 5, mode: 'code',
    color: 'violet', label: 'GRAPH', seconds: 150, xp: 480, task: 'connected components',
    description: 'Count separate groups in an undirected graph of n numbered nodes.', input: 'n = 5, edges = [[0,1],[1,2],[3,4]]', output: '2',
    signature: 'n, edges', hint: 'Build adjacency lists, then start a traversal from each unseen node.', insight: 'outer scanning plus traversal covers every component',
    tests: [{ args: [5,[[0,1],[1,2],[3,4]]], expected: 2, label: 'two groups' }, { args: [3,[[0,1],[1,2]]], expected: 1, label: 'one group' }, { args: [4,[]], expected: 4, label: 'isolated nodes' }],
  },
  {
    id: 'shortest-grid', track: 'Graphs & Grids', concept: 'Breadth-first search', level: 5, mode: 'code',
    color: 'lime', label: 'BFS', seconds: 160, xp: 500, task: 'shortest grid path',
    description: 'Return shortest moves from top-left to bottom-right through 0 cells, or -1.', input: 'grid = [[0,0,1],[1,0,0],[1,1,0]]', output: '4',
    signature: 'grid', hint: 'BFS explores all positions at distance d before distance d+1.', insight: 'an unweighted shortest path is a BFS layer count',
    tests: [{ args: [[[0,0,1],[1,0,0],[1,1,0]]], expected: 4, label: 'winding path' }, { args: [[[0]]], expected: 0, label: 'already there' }, { args: [[[0,1],[1,0]]], expected: -1, label: 'blocked' }],
  },
  {
    id: 'merge-intervals', track: 'Intervals & Greedy', concept: 'Sorted interval merging', level: 4, mode: 'code',
    color: 'cyan', label: 'MERGE', seconds: 110, xp: 380, task: 'merged intervals',
    description: 'Combine every overlapping [start, end] range.', input: 'ranges = [[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]',
    signature: 'ranges', hint: 'Sort by start; compare each range with the last merged end.', insight: 'sorting turns arbitrary overlap into neighboring overlap',
    tests: [{ args: [[[1,3],[2,6],[8,10],[15,18]]], expected: [[1,6],[8,10],[15,18]], label: 'four ranges' }, { args: [[[1,4],[4,5]]], expected: [[1,5]], label: 'touching ranges' }, { args: [[]], expected: [], label: 'empty' }],
  },
  {
    id: 'meeting-rooms', track: 'Intervals & Greedy', concept: 'Greedy end-time tracking', level: 4, mode: 'code',
    color: 'orange', label: 'GREEDY', seconds: 90, xp: 350, task: 'non-overlapping meetings',
    description: 'Return True when one person can attend every time range.', input: 'meetings = [[0,30],[35,40],[45,60]]', output: 'True',
    signature: 'meetings', hint: 'After sorting, each start must be at least the previous end.', insight: 'only adjacent intervals can conflict after sorting',
    tests: [{ args: [[[0,30],[35,40],[45,60]]], expected: true, label: 'no conflict' }, { args: [[[0,30],[5,10],[15,20]]], expected: false, label: 'overlap' }, { args: [[]], expected: true, label: 'no meetings' }],
  },
  {
    id: 'jump-game', track: 'Intervals & Greedy', concept: 'Farthest reachable frontier', level: 4, mode: 'code',
    color: 'lime', label: 'GREEDY', seconds: 100, xp: 370, task: 'reachable final index',
    description: 'Each value is your maximum jump length; return whether the end is reachable.', input: 'nums = [2, 3, 1, 1, 4]', output: 'True',
    signature: 'nums', hint: 'Track the farthest index reachable so far.', insight: 'a single frontier summarizes every earlier choice',
    tests: [{ args: [[2,3,1,1,4]], expected: true, label: 'reachable' }, { args: [[3,2,1,0,4]], expected: false, label: 'blocked' }, { args: [[0]], expected: true, label: 'already at end' }],
  },
  {
    id: 'kth-largest', track: 'Heaps', concept: 'Bounded min-heap', level: 4, mode: 'code',
    color: 'violet', label: 'HEAP', seconds: 100, xp: 370, task: 'kth largest value',
    description: 'Return the kth largest number without assuming unique values.', input: 'nums = [3,2,1,5,6,4], k = 2', output: '5',
    signature: 'nums, k', hint: 'Import heapq and keep a min-heap containing only k values.', insight: 'a size-k heap avoids sorting the entire input',
    tests: [{ args: [[3,2,1,5,6,4],2], expected: 5, label: 'k = 2' }, { args: [[3,2,3,1,2,4,5,5,6],4], expected: 4, label: 'duplicates' }, { args: [[1],1], expected: 1, label: 'one value' }],
  },
  {
    id: 'top-k-frequent', track: 'Heaps', concept: 'Frequency ranking', level: 5, mode: 'code',
    color: 'pink', label: 'HEAP', seconds: 125, xp: 420, task: 'top k frequent values',
    description: 'Return the k most common numbers, ordered by frequency then value.', input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1, 2]',
    signature: 'nums, k', hint: 'Count first, then rank pairs by negative frequency and value.', insight: 'separate frequency measurement from top-k selection',
    tests: [{ args: [[1,1,1,2,2,3],2], expected: [1,2], label: 'three values' }, { args: [[4,4,5],1], expected: [4], label: 'k = 1' }, { args: [[3,3,2,2,1],2], expected: [2,3], label: 'tie by value' }],
  },
  {
    id: 'subsets', track: 'Backtracking', concept: 'Choose-or-skip tree', level: 5, mode: 'code',
    color: 'cyan', label: 'SEARCH', seconds: 140, xp: 450, task: 'all subsets',
    description: 'Return every subset in depth-first choose-before-skip order.', input: 'nums = [1, 2]', output: '[[1,2],[1],[2],[]]',
    signature: 'nums', hint: 'At each index, recurse once with the item and once without it.', insight: 'binary choices form a complete decision tree',
    tests: [{ args: [[1,2]], expected: [[1,2],[1],[2],[]], label: '[1, 2]' }, { args: [[1]], expected: [[1],[]], label: '[1]' }, { args: [[]], expected: [[]], label: '[]' }],
  },
  {
    id: 'permutations', track: 'Backtracking', concept: 'Incremental construction', level: 5, mode: 'code',
    color: 'orange', label: 'SEARCH', seconds: 150, xp: 470, task: 'all permutations',
    description: 'Return every ordering in depth-first input order.', input: 'nums = [1, 2, 3]', output: 'six orderings',
    signature: 'nums', hint: 'Choose each unused value for the next position.', insight: 'backtracking restores state after exploring each choice',
    tests: [{ args: [[1,2]], expected: [[1,2],[2,1]], label: '[1, 2]' }, { args: [[1]], expected: [[1]], label: '[1]' }, { args: [[]], expected: [[]], label: '[]' }],
  },
  {
    id: 'tree-depth', track: 'Trees', concept: 'Recursive tree reduction', level: 4, mode: 'code',
    color: 'lime', label: 'TREE', seconds: 100, xp: 380, task: 'maximum tree depth',
    description: 'Trees use [value, left, right]; return the longest root-to-leaf node count.', input: 'tree = [3,[9,None,None],[20,[15,None,None],[7,None,None]]]', output: '3',
    signature: 'tree', hint: 'Empty trees have depth 0; otherwise use the deeper child.', insight: 'the same rule solves every subtree recursively',
    tests: [{ args: [[3,[9,null,null],[20,[15,null,null],[7,null,null]]]], expected: 3, label: 'depth three' }, { args: [[1,null,[2,null,null]]], expected: 2, label: 'right child' }, { args: [null], expected: 0, label: 'empty tree' }],
  },
  {
    id: 'tree-preorder', track: 'Trees', concept: 'Depth-first traversal order', level: 4, mode: 'code',
    color: 'violet', label: 'TREE', seconds: 110, xp: 390, task: 'preorder traversal',
    description: 'Trees use [value, left, right]; return values in root-left-right order.', input: 'tree = [1,None,[2,[3,None,None],None]]', output: '[1, 2, 3]',
    signature: 'tree', hint: 'Visit the value before recursing into its children.', insight: 'where work happens relative to recursion defines traversal order',
    tests: [{ args: [[1,null,[2,[3,null,null],null]]], expected: [1,2,3], label: 'right-heavy' }, { args: [[1,[2,null,null],[3,null,null]]], expected: [1,2,3], label: 'balanced' }, { args: [null], expected: [], label: 'empty tree' }],
  },
  {
    id: 'valid-bst', track: 'Trees', concept: 'Recursive bounds', level: 5, mode: 'code',
    color: 'pink', label: 'BST', seconds: 140, xp: 460, task: 'valid search tree',
    description: 'Trees use [value, left, right]; every left value must be smaller and right value larger.', input: 'tree = [2,[1,None,None],[3,None,None]]', output: 'True',
    signature: 'tree', hint: 'Pass an allowed lower and upper bound into each subtree.', insight: 'ancestor constraints matter, not only parent comparisons',
    tests: [{ args: [[2,[1,null,null],[3,null,null]]], expected: true, label: 'valid' }, { args: [[5,[1,null,null],[4,[3,null,null],[6,null,null]]]], expected: false, label: 'deep violation' }, { args: [null], expected: true, label: 'empty tree' }],
  },
] satisfies Drop[];

export const TRACKS = [
  { name: 'Python Foundations', goal: 'Fluent expressions and core tools' },
  { name: 'Hash Maps', goal: 'Fast lookup and frequency thinking' },
  { name: 'Two Pointers', goal: 'Eliminate work using structure' },
  { name: 'Stacks', goal: 'Model nested and next-greater state' },
  { name: 'Binary Search', goal: 'Reason about monotonic boundaries' },
  { name: 'Sliding Window', goal: 'Maintain a moving valid region' },
  { name: 'Prefix Sums', goal: 'Trade setup for instant queries' },
  { name: 'Dynamic Programming', goal: 'Reuse optimal subproblems' },
  { name: 'Graphs & Grids', goal: 'Traverse connected state spaces' },
  { name: 'Intervals & Greedy', goal: 'Make locally decisive choices' },
  { name: 'Heaps', goal: 'Maintain priority and top-k state' },
  { name: 'Backtracking', goal: 'Explore and restore decision state' },
  { name: 'Trees', goal: 'Apply recursive structure and invariants' },
] as const;
